agent.go, errors.go
Returning a typed error allows us to handle it gracefully in pions/webrtc
=> Return typed error when no candidate pairs

agent.go, candidate.go, candidate_test.go, candidatepair.go, candidatepair_test.go
Some constants were being incorrectly generated using 2^N (XOR)
instead of 1 << N. This resulted in incorrect candidate priorities
being used to evaluate candidate pairs.
Resolves #14
=> Candidate priority is incorrectly calculated

agent.go, agent_test.go, transport_test.go
Connectivity checks are done via a Ticker, the inital tick does not
happen immediately (by design) causing the startup time to be the Duration the
Ticker is created with.
This change adds another chan forceCandidateContact that can be used to
force contact at anytime. Currently it is only called on startup, but
could be useful in the future for reuse.
Resolve #15
=> Send connectivity checks right on agent start

agent.go, agent_test.go, candidate.go, gather.go, stun.go, util.go
Move code out of agent that is general to dedicated files, no logic
changes just moving.
---
Please push back if you think this is obnoxious/pointless, just making `agent.go` shorter. I saw some stuff that didn't actually need any of that state so thought would be nice.
thanks!
=> Shorten agent code

agent.go, candidate.go
If a inbound message is not associated with a valid remote STUN
candidate discard it
Resolves #20
-----
@kixelated I believe all the issues you cited are resolved when this lands.
* Remote STUN messages are checked via MessageIntegrity (so no MITM)
* Remotes can't create prflx candidates (no DoS possible)
* We discard non-STUN messages if we don't have an associated candidate
- Since we are dealing with lossy messages I think success just matters for outbound. I would prefer not to lose inbound messages from a candidate if it is valid.
=> Discard non-STUN if no associated candidate

agent.go, gather_test.go, transport_test.go
Validate all inbound binding success messages, before
peers could create valid prflx candidates without doing
a full request response
Resolves #21
=> Validate inbound success messages

agent.go
Some transactions were lost because a small bug in indexing
=> Fix handleInboundBindingSuccess bug

agent.go, agent_test.go, candidate.go, util.go
We previously didn't correctly follow [0] This updates
the agent to assert that a bindingSuccessResponse is
for the address it was sent too.
https://tools.ietf.org/html/rfc8445#section-7.2.5.2.1
=> Assert that a bindingSuccessResponse is symmetric

selection.go
Although we only nominate and select one candidate pair, since we retry the request we can end up selecting the same candidate multiple times
=> Select a pair once

README.md, transport.go
Avoid waiting for agent.onConnected in agent.connect if the agent
is closed.
Related to https://github.com/pion/webrtc/issues/642. Fixes TestPeerConnection_Close_PreICE sometimes failing in the webrtc repo.
=> Fixed closing transport during connect

agent.go, agent_test.go
When Close is called on an agent emit 'Closed'
to the connection state callback
Resolves #39
=> Emit Closed via ConnectionStateCallback

.golangci.yml, gather.go, go.mod, go.sum, stun.go, util.go
Modified gatherCandidatesReflective to respect port min and max
constraints when allocating connections for server reflexive
candidates.
Related to https://github.com/pion/webrtc/issues/668
https://github.com/pion/stun/pull/9
=> Respect port range for srv reflexive candidates

agent.go, agent_test.go, candidate.go, candidate_base.go, candidate_host.go, candidate_peer_reflexive.go, candidate_relay.go, candidate_server_reflexive.go, candidate_test.go, candidatepair.go, candidatepair_test.go, gather.go, selection.go, transport_test.go
This change will allow us to have custom logic and members
per interface type. Relay candidates will have a completely different
read loop, and candidate specific state.
Relates to #47
=> Make Candidate an interface

agent.go, candidate.go, candidate_base.go, candidate_relay.go, gather.go
* This disables all other candidates besides relay
* We hardcode networkTypes in a few places
=> WIP Turn Implementation

gather.go
Gather only asserted that it wasn't GatheringStateGathering. This
meant that if gathering was complete it would allow multiple runs.
=> Improve Gathering error handling

agent.go, agent_test.go, candidatepair.go, gather.go, selection.go, transport_test.go
Fixes #35 
This implements a basic validation schema using a checklist. We try every pair at least maxTries (7 by default see #35), and mark it as failed if we don't get a success response after that many requests. Once we get a success response, we check if it belongs to the best candidate available so far, if it does we nominate it, otherwise we continue.
Also, after a given timeout, if no candidate has been nominated, we simply choose the best valid candidate we got so far (if no candidate is valid, we mark the connection as failed).
Finally, the nomination request also has a maximum of maxTries, we mark the connection as failed if after that many attempt we fail to get a success response.
=> Adding checklist for candidate validation

agent.go, candidatepair.go
instead of indication (to support consent refreshness)
=> Use binding request for keepalive

selection.go
Receiving the message with transaction ID that is currently not in
progress is expected.
* Change output format to hexademical to improve readability
* Change log severity to warning
* Update wording (invalid -> unknown)
Fixes #59
=> Update unknown transaction ID handling for responses

agent.go, agent_test.go, candidate_host.go, candidate_peer_reflexive.go, candidate_relay.go, candidate_server_reflexive.go, gather.go, transport_test.go
Use config objects to create candidates + add optional candidateID
The CandidateID config is useful when testing, otherwise two objects won't match because of the ID
=> Use config objects to create candidates + optional CandidateID

agent.go, candidatepair.go, selection.go
This way we can identify between the valid candidate pairs, which one has been nominated.
=> Add nominated flag to candidate pair stats

README.md, agent.go, agent_test.go
time.Ticker leaks if not Stop()-ed after use.
Close connectivity interval ticker on Agent.Close() to fix leak.
---
Calling `webrtc.NewPeerConnection` and `webrtc.Close` repeatedly causes continuous increase of memory usage.
As a result of heap memory analysis using pprof, I've found that Agent.Ticker is leaked as following:
=> Fix Ticker leak

agent.go
When trickle is enabled do a connectivity check everytime a candidate
is added. Because we have a new candidate there is a chance we could
have a success this time.
=> Do connectivity check when candidate is added

README.md, agent.go, gather.go, gather_vnet_test.go
This callback can be used to exclude interfaces from gathering.
Relates to pion/webrtc#843
=> Add InterfaceFilter to AgentConfig

README.md, gather.go, gather_test.go
Use random port to gather udp candidate
This speed up the gather progress if too many connections existed
Resolve #107
=> Use random port to gather udp candidate

README.md, agent.go, agent_test.go, errors.go, go.sum
Adding configuration support for local username fragment and password, making sure we are validating values based on the RFC standard. Wrote unit test case to cover backward compatibility and test RFC standard validation.
```
go test -run TestAgentCredentials
ice ERROR: 2019/11/07 03:50:38 failed to accept local username fragment as it is less than 24 bits long
ice ERROR: 2019/11/07 03:50:38 failed to accept local password as it is less than 128 bits long
PASS
ok  	github.com/pion/ice	0.032s
```
=> Configuration support for local agent username fragment and password

mdns.go, util.go
This isn't in a hot path, so no performance hit. Also want to avoid side
effects from doing in an init
=> Seed everytime when calling generateRandString

agent.go, errors.go, mdns_test.go
Allow users to pass in a static MulticastHostName, this can be used to
connect peers in a LAN without signaling. If you set a static uFrag/uPwd
on either side and have a static hostname you can gather without knowing
an IP Address on either side.
=> Add MulticastHostName to AgentConfig

agent_test.go, candidate_relay_test.go, candidate_server_reflexive_test.go, connectivity_vnet_test.go, gather_test.go, gather_vnet_test.go, mdns_test.go, transport_test.go
Some tests using net.Conn connection are disabled for now
as it is not fully supported by WASM MVP stage.
preparation for https://github.com/pion/.goassets/pull/4
=> Support WASM build/test

candidate_relay_test.go, candidate_server_reflexive_test.go
Debian based linux uses 127.0.1.1 as a local loopback address
in some condition of the install.
ref: https://github.com/pion/ice/pull/142
=> Fix TestRelayOnlyConnection on debian

agent.go
Match behavior of adding a remote candidate
Relates to pion/webrtc#767
=> Request connectivity checks on new local candidate

agent.go, selection.go
Add error message if pingAllCandidates is called and we
have no candidate pairs. This may help users when debugging.
=> Add error message when no pairs

agent.go, candidate_server_reflexive_test.go, gather.go, gather_test.go, gather_vnet_test.go, role.go, util.go
Gather candidates of each type concurrently, this way a single slow
TURN/STUN server doesn't block the others.
We should make the entire gather process more concurrent and spawn each
gather in a separate goroutine eventually
Resolves #118
=> Gather STUN/TURN URLs concurrently

agent_test.go
Connectivity checks are over UDP, if we lost any message
message this would cause the test to fail.
Resolves #149
=> Remove taskLoopInterval from TestConnectivityLite

agent.go, candidate_base.go, candidatetype.go, gather.go, mdns.go, selection.go, transport.go, transport_test.go, util.go
Remove taskChan and make .run just take an Agent wide mutex and run the
function. These is now a blocking operation so all channels used to
communicate from it must be buffered.
After this we will slowly remove usage of .run and make things more
thread safe.
Relates to #80, #67, #2
=> Start Agent performance refactor

agent.go, gather.go
- Fix asynchronous task processing
- Make callback handler atomic/Value.
- Launch candidate callback loop in gatherCandidates().
- Asynchronously add remote candidate
- As same as mDNS candidate.
=> Fix async processing

README.md, gather.go
Fix closeable panic when conn == nil
ice WARNING: 2020/04/09 23:38:28 conn= &{{0xc0003f6d00}} , err=<nil>, a.portmax=43063 a.portmin=43061
ice WARNING: 2020/04/09 23:38:28 could not get server reflexive address udp6 stun:stun.stunprotocol.org:3478: write udp6 [::]:43062->[2600:1f16:8c5:101::108]:3478: sendto: no route to host
ice WARNING: 2020/04/09 23:38:28 conn= &{{0xc000122380}} , err=<nil>, a.portmax=43063 a.portmin=43061
ice WARNING: 2020/04/09 23:38:33 could not get server reflexive address udp4 stun:stun.stunprotocol.org:3478: read udp4 0.0.0.0:43063: i/o timeout
Fixes https://github.com/pion/ion/issues/114
=> Fix closeable panic

agent.go
Fix send on closed channel panic.
Fixes #182
=> Don't run agent task after close

agent.go, connectivity_vnet_test.go, transport.go
The selected pair must NEVER be cleared. Instead we
should keep sending connectivity checks on it. If we go to failed the
user will then create a new PeerConnection or do an iceRestart.
In the future we may support nominations, but not standardized yet.
This test asserts that we can move from
Connected -> Disconnected -> Connected
Resolves #186
=> Don't unset the selected pair on timeout

agent.go, agent_test.go, candidate.go, candidate_base.go, candidate_server_reflexive_test.go, connectivity_vnet_test.go, gather_test.go, mdns_test.go, transport.go, transport_test.go
Avoid using uninitialized object on receiving packet.
Fix routine leak in TestTimeout.
Which seems caused timeout during routine leak test which requires max 10s.
Fixes #202
Related #204
=> Fix flaky tests

agent_test.go
Task loop interval was 2s and disconnect/fail timeout was 1s.
If the first ping packet after the pair nomination was dropped,
it entered failed state.
Fixes #204
=> Fix TestAgentRestart stability

README.md, gather.go, gather_test.go
This PR enables gathering srflx candidates from `turn:` urls.
=> Allow gathering srflx candidates from turn: urls

agent.go, agent_test.go, connectivity_vnet_test.go, transport_test.go
GetRemoteUserCredentials and GetLocalUserCredentials were
not thread safe. This puts them both behind a .run
=> Make Credential getters thread safe

README.md, transport.go, transport_test.go
Instead of always returning `nil` from `Conn.LocalAddr()` and `Conn.RemoteAddr()` pick the address the selected pair or nil if there is none.
I assume there is a reason for this but I couldn't find it anywhere. Primarily motivation for doing this was having correct addresses when passing them to the quic transport in pion/webrtc.
TODO:
I ran a few circles around this because I didn't see the unexported `addr() *net.UDPAddr`.
I feel like it should be easier to get this, maybe change `CandidateRelatedAddress` slightly? But since I'm fairly new to this code I wanted to check in first and not mangle it further.
updates pion/quic#31
=> Make Transport return addresses of the current pair

agent_test.go
Wait until checking in OnSelectedCandidatePairChange callback.
related: #225
=> Stabilize callback deadlock test

connectivity_vnet_test.go
Variable `err` is unexpectedly captured by goroutine.
Fixes #229
=> Fix data race in TestWriteUseValidPair

rand_test.go
It took too long when -race is specified.
=> Reduce iteration in TestRandomGeneratorCollision

agent.go, agent_config.go
Remove candidateSelectionTimeout
The code that uses this field was removed in
e264665676a68107c582a480318880c08f2e19a5 but the field
wasn't properly removed from the public API.
=> Remove candidateSelectionTimeout

README.md, agent.go, agent_config.go, candidate.go, candidate_base.go, candidate_host.go, candidate_peer_reflexive.go, errors.go, gather.go, gather_test.go, networktype.go, networktype_test.go, tcp_ip_mux.go, tcp_ip_mux_test.go, tcp_mux.go, tcp_packet_conn.go, tcptype.go, tcptype_test.go, util.go, util_test.go
Tested on Firefox and Chrome.
The current implementation creates global TCP listeners on all allowed interfaces when `AgentConfig#NetworkTypes` includes a network with type `tcp4` or `tcp6.
The config option `TCPListenPort` should be used to set a wanted port. When set to `0`, `TCP` listening willl be disabled. This could be changed to randomly select a port.
Note: the [RFC6544](https://tools.ietf.org/html/rfc6544) states there are three TCP candidate types:
- passive (this PR, controlled role)
- active (browsers currently support this, controlling role)
- simultaneous open (both active and passive, not sure what the role would be here since it's both controlled and controlling?)
TODO: check if priority should be lower for TCP Host type candidates.
`tcpIPMux` keeps a global map of local …
=> Add support for passive ICE TCP candidates

tcp_ip_mux_test.go, tcp_mux.go
=> Remove check for ICEControlling when parsing TCP STUN message

agent_config.go, agent_test.go
Resolves #255
See #255 for details
Per discussion with @Sean-Der we decided to simply increase the maxBindingRequestTImeout from 500msec to 4000msec.
=> Increase binding req timeout value

tcp_packet_conn.go
Mutex being unlocked too soon caused a panic. See the issue for more details and a link to `pion/webrtc` issue.
Is there a better way of preventing a write to closed channel than this?
Fixes #260
=> Do not prematurely unlock mutex in handleRecv

candidate_base.go, candidate_test.go
Closes #262.
Adds the changes in determining local preference for ICE TCP candidates according to RFC 6544, section 4.2.
https://tools.ietf.org/html/rfc6544#section-4.2
The only thing I'm not sure about is the value of `otherPref`, which is currently always set to `8191`, but the RFC says the following:
> If any two candidates have the same type-preference and direction-pref, they MUST have a unique other-pref.  With this specification, this usually only happens with multi-homed hosts, in which case other-pref is the preference for the particular IP address from which the candidate was obtained.  When there is only a single IP address, this value SHOULD be set to the maximum allowed value (8191).
=> Make TCP ICE candidates have lower preference

agent.go
This operation needs to be cancelled when the candidate is closed.
Before it was only cancelled when the Agent was closed.
Resolves #299
=> Use candidate context in validateNonSTUNTraffic

candidate_base.go
Should be a pointer, not a value. Copying the atomics was causing a
race
Resolves #307
=> Fix candidateBase Marshal receiver type

agent_udpmux_test.go, udp_mux.go, udp_mux_test.go, udp_muxed_conn.go
The previous implementation of UDPMux was dropping
packets due to channel usage in the critical write path.
=> Improved performance of UDPMux

agent_udpmux_test.go, gather.go, udp_mux.go, udp_mux_test.go
Refactor UDPMux to match TCPMux patterns. The goal is to have a
collection of mux instances and no specific UDP/TCP code
Resolves #350
=> Generalize UDP and TCP Mux

agent_udpmux_test.go, udp_mux.go, udp_muxed_conn.go
If we get a packet for an address we don't know dispatch it
by ufrag still.
Resolves #357
=> Update UDPMux to dispatch inbound packets on ufrag

README.md, udp_mux.go
This fixes compilation with Go 1.13 and 1.14.
Fixes #360.
=> Use os.IsTimeout instead of os.ErrDeadlineExceeded

errors.go, gather.go, udp_mux.go
Duplicate candidates are useless, but also detrimental to how UDPMux
functions. Closing one connection for a Ufrag would end up terminating
other identital candidates for the same Ufrag.
This happens when both of the public and private IPs on a system are 
mapped to one of the same (i.e. via `Nat1To1IPs`). Adding this check 
improves the ease of deployment for pion.
=> Avoid gathering duplicate candidates

README.md, udp_mux.go, udp_mux_test.go
If no logger is passed in, it will be created.
Error running [ice-single-port](https://github.com/pion/webrtc/tree/master/examples/ice-single-port) :
invalid memory address or nil pointer dereference
=> Fix UDPMux logger

AUTHORS.txt, agent_stats.go, candidate_base.go, candidate_relay.go, candidate_test.go, gather.go
Candidates have a field `RelayProtocol` on their stat as defined [here](https://www.w3.org/TR/webrtc-stats/#dom-rtcicecandidatestats-relayprotocol):
> It is the protocol used by the endpoint to communicate with the TURN
> server. This is only present for local candidates. Valid values are
> "udp", "tcp", or "tls".
Currently, the field is populated with "udp" for all local and remote candidates of all types. Instead, we should leave it blank for all but local relay candidates in which case we should populate it with the protocol used to talk to the TURN server.
=> Populate RelayProtocol for relay candidates

agent.go, tcp_mux.go
Duplicate TCP candidates share the same candidateConn by tcpMux.GetConnByUfrag, which would be closed if started before checking
=> Fix duplicate TCP candidates

AUTHORS.txt, candidate_base.go, candidatepair_state.go, candidatepair_test.go, candidatetype.go, gather.go, ice.go, ice_test.go, url.go, url_test.go
This constant tends to cause collisions with enumerations, and is
in general a source of bugs
Related to pion/webrtc#1293
=> Remove unknown constant

agent.go
This fixes a data race where `gatherCandidateCancel` could be overwritten during cancel.
This may not fix the actual race, because I assume `gatherCandidates` shouldn't run at all after `Close`, but I'm not sure. cc: @Sean-Der 
Here's output from the race that occurs:
```
==================
WARNING: DATA RACE
Write at 0x00c000e6f710 by goroutine 385:
sync/atomic.CompareAndSwapInt32()
/usr/local/goboring/src/runtime/race_amd64.s:334 +0xb
sync/atomic.CompareAndSwapInt32()
<autogenerated>:1 +0x1e
context.(*cancelCtx).cancel()
/usr/local/goboring/src/context/context.go:401 +0x84
context.WithCancel.func1()
/usr/local/goboring/src/context/context.go:238 +0x4f
github.com/pion/ice/v2.(*Agent).Close()
/home/coder/Projects/coder/coder/vendor/github.com/pion/ice/v2/agent.go:899 +0xf2 …
```
=> Fix race condition when closing agent after gather

agent.go, udp_mux_test.go
TCP/UDP Mux would have old entries of closed PacketConns from restarted
ICE Agents. Move cleanup code from Closing the ICE Agent into a shared
function and also call it during Restart.
=> Clean ufrag from UDP/TCP Mux during ICERestart

agent.go
It was possible for the Close() function to exit without all goroutines
existing. By closing these channels before the after function, all
goroutines are forced to exit before.
=> Fix goroutine leak after close

agent.go, agent_config.go, errors.go, gather.go, gather_test.go, udp_mux_universal.go, udp_mux_universal_test.go
See reference issue for details https://github.com/pion/ice/issues/400
**Core changes:**
* Modified [UDPMux](https://github.com/pion/ice/blob/master/udp_mux.go) to additionally support Server Reflexive candidates (besides Host candidates).
* Added UDPMuxSrflx to Agent
* If UDPMuxSrflx is not provided, the original logic for server reflexive candidates is applied.
The reason why we went with 2 separate UDPMux'ex for Host and Srflx candidates is the conflicts between different candidate types on candidates gathering. Original UDPMux uses uFrag to mux connections which is fine for the case when there is a single candidate type. When there are more different candidate types the packets are getting mixed up. 
There is a possible solution to that which is using the STUN transaction ID map. The …
=> Use UDPMux for Server reflexive candidates

AUTHORS.txt, gather.go, tcp_mux.go, tcp_mux_test.go
TCPMux before would create one internal connection per ufrag. This could
cause remote IPv6 traffic to be dispatched to a local IPv4 handler (or
the inverse). The ice.Agent would then discard the traffic since a
candidate pair must be the same IP version.
This commit now creates two connections per ufrag. When requesting a
connection for a ufrag the user must specify if they want IPv4 or IPv6.
Relates to pion/webrtc#2125
Relates to pion/webrtc#1356
=> Make TCPMux IPv4/IPv6 aware

candidatepair.go, selection.go
A controlled Agent would discard incoming Binding Requests if it didn't
cause the pair to be selected. For UDP Candidate this would be
interpreted as packet loss. For TCP Candidates not responding with a
Binding Success could be interpreted as a failure.
Firefox's ICE Agent would disconnect TCP Candidates because of this
behavior.
Resolves to pion/webrtc#2125
Resolves to pion/webrtc#1356
See https://bugzilla.mozilla.org/show_bug.cgi?id=1756460
=> Don't drop Binding Requests in Controlled Agent

agent.go, gather.go
The "gatherCandidates()" function could previously leak after
close, because the WaitGroup was left unchecked.
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 883 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 883 [IO wait]:
internal/poll.runtime_pollWait(0x47f5dd8, 0x72)
/Users/runner/hostedtoolcache/go/1.17.7/x64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc0000f8a18, 0xc000080[50](https://github.com/coder/coder/runs/5275517811?check_suite_focus=true#step:7:50)0, 0x0)
/Users/runner/hostedtoolcache/go/1.17.7/x64/src/internal/poll/fd_poll_runtime.go:84 +0xbd
internal/poll.(*pollDesc).waitRead(...)
/Users/runner/hostedtoolcache/go/1.17.7/x64/src/internal/poll/fd_poll_runtime.go:89 …
```
=> Fix goroutine leak for closing while gathering

tcp_packet_conn.go
To avoid one bad connection causing locked processes/cascading failures.
When the connection is stuck, writes will not timeout and will end up holding the lock forever. Attempts to close the connections will be stuck waiting for the mutex.
=> Reduce critical section when writing with TCPMux.

agent.go, agent_udpmux_test.go, candidate_relay_test.go, candidate_server_reflexive_test.go, connectivity_vnet_test.go, gather_test.go, gather_vnet_test.go, mdns_test.go, selection.go, transport_test.go, transport_vnet_test.go, udp_mux_test.go, udp_mux_universal_test.go
Always accept Aggressive Nominations by remote agent
Relates to 18f7a214aae82a41a6d91a90a7652cf66e3e90e2
=> Enable acceptAggressiveNomination by default

agent.go, gather.go, selection.go, tcp_mux.go, tcp_packet_conn.go, udp_mux.go, udp_mux_universal.go
This PR harmonizes the use of newlines in log statements.
My custom logger was a little confused by a mix of logging statements with and without newlines.
=> No log newlines

gather.go, udp_mux.go, udp_muxed_conn.go
This PR fixes memory leaks I noticed with my SFU deployment.
- Clients performing an early termination/cancelation would cause `udpMuxedConn` to
leak addresses into `UDPMuxDefault`.
- A call to `(udpMuxedConn).Close()` would set `(udpMuxedConn).addresses` to `nil`, which prevented their deletion from `(UDPMuxDefault).addressMap`
- Small refacto of `UDPMuxDefault` that replaces `removeConn` by `RemoveConnByUfrag`
- Before that the gatherer would ignore some host candidates
- I can submit the `gather.go` updates in a separate PR if it helps land this one faster
=> fix: UDPMux memory leaks

AUTHORS.txt, agent_test.go, agent_udpmux_test.go, gather.go, gather_test.go, selection.go, tcp_mux.go, tcp_mux_multi.go, tcp_mux_multi_test.go, tcp_mux_test.go, tcp_packet_conn.go, udp_mux.go, udp_mux_multi.go, udp_mux_multi_test.go, udp_mux_test.go, udp_mux_universal.go, udp_mux_universal_test.go, udp_muxed_conn.go, udpmsghelper.go, udpmsghelper_js.go
When we have multiple host candidates and been mux to a single port, if these candidates share a same conn (either tcp or udp), they might read other's msg
cause ice connection cost long time or failed.
This should also fix #473 
Fixes #...
=> Fix muxed conn shared by candidate

external_ip_mapper.go, external_ip_mapper_test.go
If we only set v4 or v6 NAT1to1Mapping, then findExternalIP will failed for the unset ip mapper, the gatherer will complain 1:1 NAT mapping is enabled but no external IP is found, cause that candidate for udp can't be gathered.
Fixes #...
=> IpMapper return locIP if corresponding map not set

udp_mux.go, udpmsghelper.go, udpmsghelper_js_win.go
Udp mux need retrieve destination address to dispatch received packet when listen at Any address. Windows use winsock APIs to get that, but conn.FD() is not implemented on Windows. Instead it'll dispatch packet to the first candidate. It's not ideal, but it maintains the existing behavior prior to source specific dispatching.
=> Fix build failed on windows

agent.go, agent_config.go, gather.go, gather_test.go, gather_vnet_test.go, util.go
When machine's network interface have more than one ip address and user don't want expose one of these ips to remote peer, interface filter can't work in this case, so add a ip filter for that.
=> Add IPFilter to AgentConfig

udp_mux.go
ECS network might not set destination address of udp packet to local address, so we can't only rely on it to dispatch packet.
related to https://github.com/livekit/livekit/pull/1036 user report
=> Fix udpmux not work on AWS/ECS

candidate_base.go
In #252 decide to ignore the writeTo failed error with a log, application can choose callback and query state for the connection state. But if application keep sending packet during try ice restart to recover from ICEFailed, the warn log is annoying since the error is not critical and no need to process. So change it to info.
When application get ice failed and try negotiation with ice restart to recover from failed state, but keep sending packets during recover, there will be a bunch of `use of closed network connection` warn log. 
#252
=> Change writeTo failed log level to info

agent.go, agent_test.go, errors.go
Updated ICE agent restart method to cancel the current gathering and then restart the candidate gathering process.
Fixes #280
=> Cancel Previous Gathering Routine On Restart

agent.go
When duplicate candidates have been added (both NATMapping and UDPMux enabled), the candidate connection should be closed with the ignored candidate, otherwise, resource is leaked.
Fixes #...
=> Close connection if candidates already exist

agent.go, agent_config.go, gather.go, gather_test.go, gather_vnet_test.go, udp_mux.go, udp_mux_multi.go, util.go
User report that VM's public ip has been mapped to loopback interface, but pion doesn't listen/collect the loopback interface cause it can't establish the connection. This PR adds an option to enable loopback interface candidates.
Fixes #494
=> Add option to include loopback candidate

candidate_base.go
A `Candidate` with IPv6 address was formatted similar to `fe80::1:51820`.
`net.JoinHostPort` will add `[` `]` around the address if it's IPv6, so it would look like `[fe80::1]:51820` instead.
=> Fix IPv6 formatting in Candidate.String()

AUTHORS.txt, agent_udpmux_test.go, candidate_base.go, candidate_test.go
Check if connection is closed before writing anything to it.
Fixes #503
=> Check if conn is closed before writing to it.

AUTHORS.txt, agent.go
Pointer is already checked earlier in the function
=> Remove redundant check for null pointer

AUTHORS.txt, udp_mux_multi_test.go
filter out all docker bridge networks, not only default one
Fixes #523
=> Fix TestUnspecifiedUDPMux

gather.go
Since the recent changes in https://github.com/pion/ice/commit/0194bd6ce840c49dd743171e6e4cab3ddf3c5beb it appears that TLS over TCP is no longer working properly unless you explicitly provide the InsecureSkipVerify flag to the tls.Config (by providing it when the agent is instantiated). The call to tls.Client() requires either ServerName or InsecureSkipVerify to be set, and since you most likely don't want to enable InsecureSkipVerify this change does what is necessary. The call to conn.HandshakeContext following this will always fail with the error `Failed to connect to relay: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config` unless InsecureSkipVerify is enabled.
The behaviour this pull request sets for the tls.Config is also already used by the …
=> Add ServerName to tlsConfig for TLS-over-TCP

gather.go, gather_test.go
Canceling previous gathering does not happen synchronously. If it takes a little bit longer, it can close newly created `gatherCandidateDone` channel.  If we pass channel to the `gatherCandidates` function, it will always close its done channel and only the latest done channel will be available in `gatherCandidateDone`.
Fixes #445
=> Fix gathering candidates race condition

gather.go, gather_test.go
PR #496 added a mechanism to close connections of duplicate candidates and avoid memory leaks. When UDPMuxDefault and NAT1To1IPs are used together, candidates may share the same connection, and candidates may be equal, since their IPs are overridden by the one specified in NAT1To1IPs. When a duplicate candidate is found, its connection is closed, making impossible to use any other candidate that shares the same connection.
This PR fixes the issue as it prevents duplicate candidates from creating connections and getting their connection closed.
Fixes #505
Related to https://github.com/aler9/mediamtx/issues/1680
=> Fix regression with UDPMuxDefault and NAT1To1IPs

agent.go, agent_active_tcp_test.go, agent_config.go, agent_test.go, candidate_base.go, candidate_peer_reflexive.go, candidate_test.go, candidatetype.go, candidatetype_test.go, gather.go, gather_test.go
This PR implements support for active TCP candidates as specified in [RFC6544](https://datatracker.ietf.org/doc/html/rfc6544)
Open issue: local active TCP candidate can be connected only with 1 remote.
=> Support active TCP candidates (RFC6544)

AUTHORS.txt, candidate_peer_reflexive.go
Reference: https://github.com/pion/randutil/pull/25
=> fix: use global id generator to reduce allocations

active_tcp.go, active_tcp_test.go, agent.go, agent_config.go, agent_test.go, candidate_base.go, candidate_test.go, gather_test.go
This is undoing my revert in abc1ca33b5557f51f94152d0b2442f039a9256b6
I have also
* Added a test to make sure we don't block the main thread
* Added a config option so it can be disabled
I would like to have it on by default to benefit users as much as possible. I would prefer if pion/ice connected in as many networks as possible. It can be turned off if users wish to conserve resources though.
=> Implement Active ICE TCP Candidates

agent.go, agent_test.go
This is analogue to `GetLocalCandidates()` and provides the user with the ability to get a slice of previously added remote candidates without keeping track of them in the application code.
=> Add `GetRemoteCandidates()`

gather.go
Printf arguments weren't passed to the logger.
=> Fix connection close log

AUTHORS.txt, agent.go
When ICE times out and fails, all candidates are deleted.
That means all the candidates are closed and their underlying conns are clsoed.
But, the selected pair could still be valid. On a subsequenct `Write`, ICE transport conn will get the selected pair and write to the pair. As the pair is still valid, write will flow through to the local candidate `writeTo`.
But, as all candidates and their underlying conns are closed, `Write` will return a `io.ErrClosedPipe` error.
There are cases where it is not ignored and causes a broken pipe after an ICERestart.
When the `Write` error propagates back to sctp/association, the writeLoop is exited.
So, sending data channel traffic after a successful ICERestart still fails as the SCTP association errored out and write loop exited.
I have copied the …
=> Clear selected pair on ICE failed

AUTHORS.txt, tcp_packet_conn.go
Safari and iOS Chrome (WebKit) sometimes opens multiple TCP connections that end up being part of the same `tcpPacketConn` object in `TCPMuxDefault`. After some time, the extra connection is closed even thought the main one is still operational. In this case, the entire peer connection gets disconnected. Instead, we probably only want to close the entire connection only once there is no other open TCP connection (this PR).
To be honest, I am not sure why Safari and iOS Chrome do this. However, there is probably no chance fixing it there.
Attaching a log of the duplicite connection that ends up in the same `tcpPacketConn` made by iOS Chrome:
```
ice INFO: 2023/09/05 09:43:21 Listening TCP on 0.0.0.0:443
pc INFO: 2023/09/05 09:45:35 signaling state changed to have-remote-offer
ice WARNING: …
```
=> Only propagate connection closure errors for the last connection.

agent.go, agent_get_best_valid_candidate_pair_test.go, candidatepair.go
On an ICE restart in controlled mode, seeing incoming messages getting discarded to due to username mismatch. That is because the broswer is still using its old candidate and user name. As the controlled agent waits for `useCandidate` from the controlling agent, the controlled agent does not get to connected/nominated state inspite of getting several success responses. Suspect the controlling side does not have `useCandidate` for the new pair and it is still sending it for the old pair. Logging more details in trace to understand it better.
=> Trace log inbound messages

tcp_mux.go, tcp_mux_test.go, tcp_packet_conn.go
Reduce read buf of first stun message.
Add timeout to read first message to clean interrupted connection earlier.
Add alive duration for gather to access connection created from stun bind, avoid connection leak from the malicious client.
=> Refine TCPMux memory usage

agent.go, agent_handlers.go, agent_handlers_test.go
Ice update connection state callbacks need to happen sequentially otherwise a later callback could overwrite a newer callback. 
Fixes: #624
=> Ensure sequential execution of connection state callbacks

candidate_relay.go, gather.go, ice.go
Today, all relay candidates from Pion have the same priority. This PR attempts to reproduce libwebrtc's behavior, where the TURN servers candidates priority is based on the underlying relay protocol. UDP are preferred over TCP, which are preferred over the TLS options. 
We reuse the same factors as libwebrtc:
https://github.com/mozilla/libwebrtc/blob/1389c76d9c79839a2ca069df1db48aa3f2e6a1ac/p2p/base/turn_port.cc#L61
=> Prioritize TURN servers according to they relay protocol

candidatepair_state.go
Fixes #571 
@Sean-Der This is another unfortunate instance of an untyped enum. What do you think about fixing this instance as well?
It will break the API, however just like already had to do for the `ConnectionState` enum.
See also: https://github.com/pion/webrtc/pull/2471#issuecomment-1546976185
=> Fix type of CandidatePairState constants

errors.go, udp_mux.go, udp_muxed_conn.go
UDPMux is using a map to lookup addresses of each packets. Unfortunately the key is based on a string and each time we want to check the map, a conversion of the UDP address to string is made (.String()) which is expensive.
This CR replace the string key by a binary key called ipPort. This structure contains a netip.Addr field and ipPort could be used as a map key
=> Improve performance of UDPMux map lookups

agent.go, agent_config.go, gather.go
Allows to configure STUN timeout from the config
Resolves https://github.com/pion/webrtc/issues/2668
=> Expose stunGatherTimeout in Agent struct

agent.go
we're seeing high `runtime.siftdownTimer` cpu on some busy nodes and profiling indicates there are ~20k timers allocated here. recreating these on every loop is inefficient.
=> Reuse connectivity check ticker

gather.go
Most error message in gatherCandidatesSrflx and gatherCandidatesSrflxUDPMux include the network in them but not the one when failing to Resolve the host.
Fixes #...
=> Add network to resolve stun host error message

udp_mux_test.go, udp_muxed_conn.go
```
BenchmarkAddressEncoding
BenchmarkAddressEncoding/encode
BenchmarkAddressEncoding/encode-10         	63219590	        16.10 ns/op	       0 B/op	       0 allocs/op
BenchmarkAddressEncoding/decode
BenchmarkAddressEncoding/decode-10         	15798038	        74.70 ns/op	      80 B/op	       3 allocs/op
```
vs
```
BenchmarkAddressEncoding
BenchmarkAddressEncoding/encode
BenchmarkAddressEncoding/encode-10         	288006478	         4.084 ns/op	       0 B/op	       0 allocs/op
BenchmarkAddressEncoding/decode
BenchmarkAddressEncoding/decode-10         	27043725	        43.38 ns/op	      64 B/op	       2 allocs/op
```
=> Reduce allocation in udp muxed conn addr decode

udp_muxed_conn.go
write returns `io.ErrClosedPipe` but read returns `io.EOF`...
=> Return io.EOF from closed udpMuxedConn

agent.go, agent_config.go, selection.go, selection_test.go
Allow the user to perform custom processing for inbound STUN Binding requests. This allows users to do some of the following
* Log incoming Binding Requests for debugging
* Implement draft-thatcher-ice-renomination
* Implement custom CandidatePair switching logic
Resolves pion/webrtc#2539
Resolves pion/webrtc#2585
Resolves #623
=> Add BindingRequestHandler

candidate_base.go, candidate_test.go
This reverts commit e1c2d85530f0f9e96935c3598cc68b6c596c1a39.
In that commit, active time was changed from time.Time to
Unix time in order to avoid allocations.  Unfortunately, that
has the side effect of discarding the monotonic component of
time.Time, and therefore makes our code vulnerable to stepping
of the system clock.
Fixes #697
=> Revert "Avoid allocation storing last active time"

agent.go, agent_handlers.go, agent_handlers_test.go, selection_test.go
This is already fixed on master. I've cherry picked 2 commits: https://github.com/pion/ice/commit/d17be4df3b49c712adf6c2c9ab08a5c4c87676f5 & https://github.com/pion/ice/commit/67cc918a518d3b3dd1887b07434331dabc846702
Since `pion/webrtc/v3` depends on `pion/ice/v2` it'd be nice if we can have a `v2` release with these two commits.
=> Fix Callback ordering for ConnectionState

agent.go, agent_handlers.go, agent_handlers_test.go, agent_test.go
This ensures no goroutines are running when an ICE agent closes. I'd also like to backport this into v2 so that webrtc/v3 can get it.
=> Cleanly close agent goroutines

candidate_base.go, candidate_test.go
Link-local IPv6 addresses may have ZoneID attached at the end. It has local meaning only and should not be send to other parties. This change removes ZoneID from generated candidate string, and ignores ZoneID when received candidate is parsed.
=> Remove IPv6 ZoneID from ICE candidates

candidate_base.go, candidate_test.go
Link-local IPv6 addresses may have ZoneID attached at the end. It has local meaning only and should not be send to other parties. This change removes ZoneID from generated candidate string, and ignores ZoneID when received candidate is parsed.
It is already merged to master, this cherry-pick is for v2.
=> Remove IPv6 ZoneID from ICE candidates (#704)

errors.go, internal/taskloop/taskloop.go
Libraries use errors.Is to catch this error. Allocating a new one inside internal breaks that
=> Don't allocate new error inside TaskLoop

agent.go, agent_handlers.go, agent_handlers_test.go, agent_test.go
This is part of the epic to get a PeerConnection to have a GracefulClose.
=> Add GracefulClose

active_tcp_test.go, agent_get_best_available_candidate_pair_test.go, agent_get_best_valid_candidate_pair_test.go, agent_on_selected_candidate_pair_change_test.go, agent_test.go, agent_udpmux_test.go, candidate_relay_test.go, candidate_server_reflexive_test.go, connectivity_vnet_test.go, gather_test.go, gather_vnet_test.go, go.mod, go.sum, mdns_test.go, transport_test.go, transport_vnet_test.go, udp_mux_test.go
this will clear the noise for when a test starts up with unexpected goroutine(s)
=> tests: Clean up Agents more aggressively

agent.go, internal/taskloop/taskloop.go
There's a case in webrtc GracefulClose (https://github.com/pion/webrtc/pull/2847/files#diff-61936a3824ea2f65378ca63d509769a4dc6b52a1685845f764089fe03de2f4c3R213-R216) where it would be beneficial to wait for the ICE agent to gracefully close but due to how Mux works, it's hard to thread it through without calling GracefulClose and then Close on the agent. That makes an error happen that doesn't seem necessary. If you close twice, that feels okay.
=> Allow multiple agent.Close

candidate_relay.go, gather.go, ice.go
Cherrypick from master (since we will keep using v2 for some time)
Match libwebrtc's TURN protocol priority (TCP vs UDP vs TLS)
Fixes reproducibility issues as seen in the field
=> [Cherrypick] Match libwebrtc protocol priority

active_tcp_test.go
Assert that a remote Passive TCP candidate doesn't cause a TCP connection to be started.
Resolves pion/webrtc#2782
=> Add test that NetworkTypes is respected

active_tcp_test.go, agent.go
Before if a user disabled TCPv6 (but enabled TCPv4) we would incorrectly start TCP connections over TCPv6 still.
Resolves pion/webrtc#2782
=> Take TCP Family into account before connecting

gather.go
Cherrypick from master branch (we will keep using the v2 for some time)
Add network to resolve stun host error message
Most error message in gatherCandidatesSrflx and gatherCandidatesSrflxUDPMux include the network in them but not the one when failing to Resolve the host.
Will help troubleshooting problems in the field
=> [Cherrypick] Improve STUN resolution error message

agent.go, agent_stats.go, agent_test.go, candidatepair.go, selection.go
Use the round trip time measurement to populate RTT fields in CandidatePairStats.
=> Add round trip time measurement to candidate pair

udp_mux_test.go
Minor change to this test to stop using sha1 and remove the linter exceptions.
=> Switch udp_mux_test to use sha256 instead of sha1

candidate_base.go
Reduce GC Pressure from Frequent ICE Gathering Events
Fixes #737
=> fix: Reduce GC Pressure from Frequent ICE Gathering Events #737

agent.go, agent_config.go, agent_test.go, selection.go
There could be a mismatch between the two ends in candidate priority
when using peer reflexive. It happens in the following scenario
1. Client has two srflx candidates.
a. The first one gets discovered by LiveKit server as prflx.
b. The second one gets added via ice-trickle first and then
gets a STUN ping. So, it is srflx remote candidate from
server's point-of-view.
2. This leads to a priority issue.
a. Both candidates have same priority from client's point-of-view
(both are srflx).
b. But, from server's point-of-view, the first candidate has
higher priority (prflx).
3. The first candidate establishes connectivity and becomes
the selected pair (client is ICE controlling and server is
ICE controlled, server is in ICE lite).
4. libwebrtc does a sort and switch some time later based on RTT. …
=> Accept use-candidate for ice-lite

net.go
Pass ipv6 zone param to `net.ListenUDP`. Also checked that it's specified in all other calls of `net.ListenUDP`. Tested it locally with ipv6 link-local and global unicast addresses. 
However, should I add a unit test for that @Sean-Der? I could add it in the [gather_test.go](https://github.com/pion/ice/blob/master/gather_test.go#L33), but it would be host specific and require an assigned ipv6 address.
Also don't forget to backport to v3, because ipv6 link-local addresses appeared in v3.
Fixes #742
=> #742 net: pass ipv6 zone param to net.ListenUDP

agent.go, agent_config.go, gather_vnet_test.go, net.go, net_test.go, udp_mux_multi.go
This should make it clear that you need to return `true` to keep it and `false` to exclude.
Similar MR in pion/webrtc: https://github.com/pion/webrtc/pull/2958.
None
=> refactor: use named return val for IP/if filter

agent_config.go
Update documentation for KeepaliveInterval to match defaultKeepaliveInterval constant
Fixes #...
=> docs(agent_config.go): update KeepaliveInterval default value to 2 sec

agent_handlers.go
We were noticing (in rare circumstances) nil pointer dereference panics from this part of the code. This PR adds a nil check to ensure that the function really exists and wasn't set to nil.
=> Add nil checks to agent_handlers

candidate.go, candidate_base.go, candidate_test.go
Added `AddExtension` and `RemoveExtension` methods to `ICECandidate`, allowing extensions to be managed dynamically.
Ensure that `TCPType` is stored in one place (candidate.TCPType)
This is required for https://github.com/pion/ice/issues/757 and by extension https://github.com/pion/webrtc/issues/2993 and some other..
=> Add methods to add and remove extensions

candidate_base.go, candidate_test.go
While not spec compliant, some implementations allow for empty extension values. This aligns with our behavior for empty foundation values. And makes the parser more forgiving for bad implementations.
=> Allow for empty extension values

agent.go, agent_test.go
Include ufrag extension in the ICE candidates generated by the ICE agent
Fixes https://github.com/pion/ice/issues/757
based on: https://github.com/pion/ice/pull/758
=> Include ufrag extension

agent.go, agent_stats.go, agent_test.go, candidatepair.go, selection.go, stats.go
These details will provide information for understanding
connectivity issue.
=> Add Req/Res count/time to candidate stats

agent.go, agent_test.go
Pion incorrectly resets the consent timer when sending any traffic. 
The consent timer must only be reset on STUN traffic.
RFC 7675
> Consent expires after 30 seconds.  That is, if a valid STUN binding
> response has not been received from the remote peer's transport
> address in 30 seconds, the endpoint MUST cease transmission on that
> 5-tuple.  STUN consent responses received after consent expiry do not
> re-establish consent and may be discarded or cause an ICMP error.
=> Always send KeepAlives

.golangci.yml, active_tcp_test.go, agent_handlers_test.go, agent_test.go, agent_udpmux_test.go, candidate_relay_test.go, candidate_server_reflexive_test.go, candidate_test.go, candidatepair_test.go, connectivity_vnet_test.go, errors.go, gather_test.go, gather_vnet_test.go, icecontrol_test.go, mdns_test.go, net_test.go, networktype_test.go, priority_test.go, rand_test.go, selection_test.go, tcp_mux_multi_test.go, tcp_mux_test.go, transport_test.go, transport_vnet_test.go, udp_mux_multi_test.go, udp_mux_test.go, udp_mux_universal_test.go, usecandidate_test.go
Use testify's assert package instead of the standard library's testing package.
=> Update lint rules, force testify/assert for tests

active_tcp.go
Replace manual atomic operations with atomic.Bool type for better type safety and cleaner code. This modernizes the atomic usage pattern from atomic.LoadInt32/StoreInt32 to the newer Load/Store methods on atomic.Bool.
- Update activeTCPConn.closed field type from int32 to atomic.Bool
- Replace atomic.LoadInt32(&a.closed) with a.closed.Load()
- Replace atomic.StoreInt32(&a.closed, 1) with a.closed.Store(true)
All existing functionality preserved with improved type safety.
=> Change activeTCPConn.close to atomic.Bool

agent.go, agent_options.go, agent_options_test.go, errors.go, renomination.go, renomination_test.go, selection.go
Adds support for renomination following https://datatracker.ietf.org/doc/html/draft-thatcher-ice-renomination-01.
=> Add support for renomination

agent_config.go
Simplifies some logic in `agent_config.go`. I'm assuming it was written before go 1.21 introduced this, but it's equivalent logic and is easier to read.
N/A
=> Replace verbose check with slices.Contains in agent_config

agent_config.go, agent_config_test.go
Defaults relay-only agent candidate types acceptance wait to zero
Fixes #324
=> Set default accept wait for relay-only candidate to 0
