pion/ice

agent.go

Don't modify config.LoggerFactory

---

agent.go
agent_test.go

When we get an inbound message assert these values, also discard any
other packet types besides binding. In the future we should extend to
handle inbound error messages
Resolves #19
----
Still need to write tests, but after #15 lands and I rebase this would appreciate if people could help me manually test everything (before I make a stupid mistake)

Assert MessageIntegrity/Username for inbound

---

agent.go
agent_test.go
errors.go
transport.go

Check was lost, also add tests so we don't regress again

Assert that agent isn't started twice

---

agent.go

Both methods pretty much do the same

refactor handleInboundControlling/Controlled

---

agent.go
agent_test.go
selection.go
transport.go

Implement regular nomination

---

agent.go
candidatepair.go

Handle INDICATION messages

---

README.md
transport_test.go

Fixes #49
Details are explained in the issue #49

Fix the test incorrectly failing

---

errors.go
url.go

Add Username/Password to URL

---

agent.go
agent_test.go
errors.go
gather.go
transport_test.go

Add trickle support

---

gather.go

Modify gathering process to be completely parallel

---

gather.go

Before we would iterate all interfaces and block until all had
completed. Instead return when we get the first candidate.
Resolves #58

Only take the first result for ServerReflexive

---

gather.go

We need to hold the same socket when gathering ServerReflexive
candidates. If we Open -> Close -> Open the port we have selected could
quickly be taken by another process
Resolves #63

Fix ServerReflexive race condition

---

candidate_relay.go

Wasteful to use just indications

Use ChannelBind for TURN Permissions

---

agent.go
agent_test.go
candidate.go
candidate_base.go
candidate_host.go
candidate_peer_reflexive.go
candidate_relay.go
candidate_server_reflexive.go
errors.go
gather.go
go.mod
go.sum
mdns.go
mdns_test.go
transport_test.go

Add mDNS Host Candidate support
Relates to pion/webrtc#699

Add mDNS Host Candidate support

---

agent.go
agent_test.go
candidate.go
candidate_base.go
candidate_host.go
candidate_peer_reflexive.go
candidate_relay.go
candidate_server_reflexive.go
candidatepair.go
candidatepair_state.go
mdns.go
selection.go
stats.go
util.go

Related to https://github.com/pion/webrtc/pull/721

Initial stats API

---

agent.go

If we are unable to bind continue Agent startup but without mDNS.
Log an error to help debugging

If mDNS fails to listen fallback to non-mDNS

---

gather.go

The candidate is added before starting, so that means the connection may be nil on write (when pinging for example).

Check for nil connection in candidate

---

agent.go
agent_test.go

Procted the selected candidate pair by a RWMutex so we don't need to relay in the agent taskloop in order to use this method

avoid agent.run for getSelectedPair

---

candidate_base.go

- Use atomics for lastReceived and lastSent fields
- the lock around resolvedAddr and conn were not being used, so I removed it

Improve candidate base locking mechanism

---

transport.go
transport_test.go

Add transport stats

---

transport.go

Fix alignment for 32bits

---

.travis.yml
gather.go

Don't assume connection is present if there is an error in listenUDP

Fix connection nil pointer

---

url.go

Remove some unnecessary repetitions.

Clean up switch conditions

---

.github/lint-commit-message.sh
.github/release
.travis.yml

feat: semantic release support

---

candidate_relay_test.go
candidate_server_reflexive_test.go
gather.go
go.mod
go.sum

Use v2, should have no client changes

Bump pion/turn

---

.golangci.yml
.travis.yml
agent.go
agent_test.go
candidate_base.go
gather.go
networktype.go
transport.go
transport_test.go

Fix whitespace error.
Disable dogsled and godox.
preparing pion/.goassets#4

Upgrade golangci-lint to 1.19.1

---

agent.go
gather.go

Call callbacks serially instead of running asynchronously.
Fix https://gophers.slack.com/archives/CAK2124AG/p1585817311280500

Fix candidate/state callback order

---

agent.go
agent_config.go
agent_test.go
connectivity_vnet_test.go
go.mod
transport_test.go

This needs to be done to implement ICE Restarts.
This is a smaller first PR. Will follow up with another one that implements restarts.

Move to /v2 and Implement ICE Failures

---

agent.go

It should use mutex, otherwise it can enter twice before setting
haveStarted to true.

Fix startConnectivityChecks multiple run guard

---

agent_test.go

It failed when accepting routine is not started faster than dial.
Part of #204

Fix TestConnectivityOnStartup

---

selection.go

Before then nominating a candidate pair we limited the
amount of requests we sent, and would set the connection
to failed.
This change removes that limit, and instead uses the Disconnected+Failed
timer to control this. I found this when debugging an unrelated thing,
and was suprised by the behavior. I didn't find anything in the spec
that mentioned this, and isn't a knob that users will understand how to
control easily.

Remove nominationRequestCount

---

gather.go
gather_test.go

This was an especially noticable issue in an environment where all UDP
was blocked, then we waited for STUN to timeout (5 seconds) before trying
TCP/turn

gather all candidate types in parallel

---

agent.go
agent_test.go

Need by pion/webrtc for ICE Restarts
Relates to pion/webrtc#1251

Add GetRemoteUserCredentials

---

README.md
util.go
util_test.go

This is just a rebase of @buptczq patch because it seems super useful.
(closes #176)

Fix IPv6 addresses gathering

---

agent.go
gather.go

Instead keep the channel around the entire time, and use
the same thread to distribute state changes and candidates.
Resolves #217

Don't re-create chanCandidate every gather

---

agent.go
agent_stats.go
agent_test.go
candidate.go
candidate_base.go
context.go
gather.go
transport.go
transport_test.go

- Refactor agent task runner
- Control blocking tasks by context
- Add tests to check deadlock by calling Close/Restart in state change callback
- Remove unnecessary chan
- Fix deadlock in SelectedCandidatePairChange
- Call handler in different routine

Refactor agent task runner

---

connectivity_vnet_test.go
transport_test.go
transport_vnet_test.go

Avoid being affected by bridged network interfaces.
Fixes #230

Run TestRemoteLocalAddr in VNet

---

agent.go
gather.go

Multiple candidate gathering routine were executed in parallel
when Restart() called immediately after previous start of gathering.
Cancel previous gathering by context to prevent mixing candidates
from two routines.
Fixes #236
Related #217
Fixes https://github.com/pion/webrtc/issues/1299

Prevent multiple gathering in parallel

---

gather.go
gather_vnet_test.go

Clean-up turn connection if task run failed.
Fixes #216
branched from #231

Fix turn client routine leak on close

---

candidate_base.go

To ensure recvLoop is unblocked.
Possibly avoid https://github.com/pion/webrtc/issues/1311 (not sure)

Set Conn.SetDeadline on candidate close

---

candidate_base.go

Instead check `closeCh` inside close. The current pattern
will cause issues if a packet is in flight.
The alternative is to add a nil check in writeTo, but that would
require locking around writes.
Resolves #247

Don't unset conn in candidate_base

---

gather.go
tcp_mux.go

fix nogo warnings on logs

---

candidate.go
candidate_base.go
candidate_test.go

Both of these things were handled in the SDP package, bringing them into ICE.

Foundation and TCPType Support

---

README.md
agent_test.go
selection.go

ICE-lite Agent doesn't detect disconnects

Add failing test for #288

---

agent.go
agent_stats.go
agent_test.go
candidate.go
candidate_base.go
candidatepair.go
candidatepair_test.go
selection.go
transport.go
transport_test.go

Implement GetSelectedCandidatePair

---

agent_udpmux_test.go
gather.go
udp_mux.go
udp_mux_test.go
udp_muxed_conn.go

improved buffer handling and prevents channel clogging

Improve UDPMux performance

---

udp_mux.go

accidentally left in the last PR

Remove print line

---

agent_udpmux_test.go
udp_mux.go
udp_mux_test.go
udp_muxed_conn.go

Fix UDPMux read/write race condition

---

candidate_base.go
candidatepair_state.go
candidatepair_test.go
candidatetype.go
gather.go
ice.go
ice_test.go
url.go
url_test.go

We will re-do this in the future, but need to keep it for a major
release.
Resolves #385

Revert "Remove unknown constant"

---

gather.go

Before we would only listen on the first. If the first interface isn't the default for the host no traffic would be received.

Update UDPMux to listen on all interfaces 

---

candidate_base.go

Support missing foundation candidates with additional attributes
Resolves #390

Improve parsing candidates with missing Foundation

---

gather.go

This was causing a 5s delay when closing the agent.

Fix close delay collecting STUN candidates

---

AUTHORS.txt
agent.go
agent_config.go
agent_test.go
selection.go

Add config for accept aggressive nomination, it is useful for compatible with chrome or other clients use aggressive nominate to update nominate candidate pairs.
Fixes #440

Add option for accept aggressive nominate

---

agent.go
udp_mux_universal.go

Minor tweaks to improve log traces and error output

---

tcp_mux.go
tcp_packet_conn.go

Previously `(*TCPMux).RemoveConnByUfrag` would close the connections while holding its lock, but it is possible for closing to block and/or take a while.
If closing one of the connections blocks (which was occurring rarely due to blocking on a channel send), then the entire `TCPMux` would deadlock and all further operations with the ICE agent would end up getting blocked due to tying up the task loop.
We have not seen any more deadlocks on our servers since applying this patch.

Attempt to fix deadlock in TCPMux

---

candidate_base.go

Do not show a warning when reading from a closed connection

---

agent.go
agent_config.go
agent_test.go
agent_udpmux_test.go
connectivity_vnet_test.go
examples/ping-pong/main.go
external_ip_mapper.go
external_ip_mapper_test.go
gather.go
gather_test.go
gather_vnet_test.go
net.go
selection.go
tcp_mux.go
tcp_mux_multi_test.go
tcp_mux_test.go
tcp_packet_conn.go
transport.go
transport_test.go
udp_mux.go
udp_mux_multi_test.go
udp_mux_test.go
udp_mux_universal.go
udp_mux_universal_test.go
udp_muxed_conn.go

Comments should start with an uppercase letter.

Fix comment capitalization

---

agent.go
errors.go
gather.go
tcp_mux.go
tcp_mux_test.go

Simplify handling if no TCP mux is configured

---

transport.go

- Change bytesReceived and bytesSent fields from uint64 to atomic.Uint64
- Replace atomic.LoadUint64 calls with Load() method calls
- Replace atomic.AddUint64 calls with Add() method calls
This modernizes the code to use Go's newer atomic types introduced in Go 1.19,
providing better type safety and cleaner API

Use atomic.Uint64 for thread-safe byte counters

---

agent.go
agent_test.go

Detect if remote has a role conflict and resolve it as defined by RFC 8445 section-7.3.1.1
Resolves #359

Implement ICE Role conflict resolution

---

tcp_mux_multi_test.go
tcp_packet_conn_test.go
udp_mux_multi_test.go
udp_mux_test.go
udp_mux_universal_test.go

Improves code coverage for various tests.
n/a

Improve test coverage for various tests

---

active_tcp_test.go
addr_test.go
agent_handlers_test.go
agent_test.go
candidatepair_test.go
candidatetype_test.go
net_test.go
networktype_test.go
role_test.go
selection_test.go
transport_test.go
udp_mux_test.go
usecandidate_test.go

Similar to my previous effort, this adds tests to improve code coverage.
The breaking change was moved to #812 
The slices rework was moved to #813 
N/A

Add more tests to improve code coverage

---

udp_mux_test.go
udp_muxed_conn.go

Saw this while fixing the tests on windows.

Remove nolint, validate port
